configfile: 'config.yml'


subworkflow basecalling:
    workdir:
        '../../nanopore_basecalling_pipeline/pipeline'
    configfile:
        '../../nanopore_basecalling_pipeline/pipeline/config.yml'


include: '../rules/mapping.snakefile'
include: '../rules/apa.snakefile'
include: '../rules/assembly.snakefile'
include: '../rules/modifications.snakefile'

def get_all_conds(comps):
    all_conds = set()
    for comp in comps:
        treat, cntrl = comp.split('_vs_')
        all_conds.add(treat)
        all_conds.add(cntrl)
    return all_conds

rule all:
    input:
        expand(
            ['apa_results/{comp}.apa_results.bed',
             'modifications/{comp}.der_sites_thresholded.bed'],
            comp=config['comparisons'],
        ),
        expand(
            'aligned_data/pooled/{cond}.bam',
            cond=get_all_conds(config['comparisons'])
        ),
        'assembly/merged_nanopore_assembly.gtf'