configfile: 'config.yml'

include: '../rules/data_cleaning.snakefile'
include: '../rules/apa.snakefile'


rule all:
    input:
        'apa_results/{comp}.apa_results.bed'.format(comp=config['comparison'])